name: tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  tox:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - uses: actions/cache@v2
        with:
          path: |
            .tox
            .mypy_cache
          key: ${{ runner.os }}-tox-${{ hashFiles('tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-tox-

      - name: Install tox
        run: pip install tox

      - name: Run tox
        # Instead of running pre-commit through tox, run it as a GitHub action
        # which uses caching.
        run: TOX_SKIP_ENV=pre-commit PY_COLORS=1 TOX_PARALLEL_NO_SPINNER=1 tox

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
